# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20190215_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='group',
            field=models.CharField(default=b'', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(default=b'', max_length=250),
        ),
    ]
