# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-26 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20190218_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_user',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
