# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-24 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20181224_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
